<?php
/**
 * @package     Joomla.Site
 * @subpackage  com_content
 *
 * @copyright   Copyright (C) 2005 - 2021 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;
use Joomla\CMS\Factory;
use Joomla\CMS\Language\Associations;
use Joomla\CMS\Layout\LayoutHelper;
use Joomla\CMS\Router\Route;
use Joomla\CMS\Uri\Uri;
use Joomla\Component\Content\Administrator\Extension\ContentComponent;
use T4\Helper\J3J4;

JHtml::addIncludePath(JPATH_COMPONENT . '/helpers/html');
JHtml::_('bootstrap.tooltip');
if(version_compare(JVERSION, '4','lt')){
JHtml::_('behavior.framework');
}

require_once(__DIR__.'/../../../helper.php');

// Create a shortcut for params.
$params = $this->item->params;
$images  = json_decode($this->item->images);
$canEdit = $this->item->params->get('access-edit');
$info    = $params->get('info_block_position', 0);

$aInfo1 = ($params->get('show_publish_date') || $params->get('show_category') || $params->get('show_parent_category') || $params->get('show_author'));
$aInfo2 = ($params->get('show_create_date') || $params->get('show_modify_date') || $params->get('show_hits'));
$topInfo = ($aInfo1 && $info != 1) || ($aInfo2 && $info == 0);
$botInfo = ($aInfo1 && $info == 1) || ($aInfo2 && $info != 0);
$icons = $params->get('access-edit') || $params->get('show_print_icon') || $params->get('show_email_icon');

// Check if associations are implemented. If they are, define the parameter.
$assocParam = (JLanguageAssociations::isEnabled() && $params->get('show_associations'));

if(version_compare(JVERSION, '4', 'ge')){
  $currentDate       = Factory::getDate()->format('Y-m-d H:i:s');
  $isExpired         = !is_null($this->item->publish_down) && $this->item->publish_down < $currentDate;
  $isNotPublishedYet = $this->item->publish_up > $currentDate;
  $isUnpublished     = $this->item->state == ContentComponent::CONDITION_UNPUBLISHED || $isNotPublishedYet || $isExpired;
}else{
  $isExpired         = (strtotime($this->item->publish_down) < strtotime(Factory::getDate())) && $this->item->publish_down != Factory::getDbo()->getNullDate();
  $isNotPublishedYet = strtotime($this->item->publish_up) > strtotime(Factory::getDate());
  $isUnpublished     = J3J4::checkUnpublishedContent($this->item);
}

// update catslug if not exists - compatible with 2.5
if (empty ($this->item->catslug)) {
  $this->item->catslug = $this->item->category_alias ? ($this->item->catid.':'.$this->item->category_alias) : $this->item->catid;
}

// Get Extrafields
$customs      = JATemplateHelper::getCustomFields($this->item->id, 'article');
$extrafields = new JRegistry($this->item->attribs);
$businessTime = empty($customs['business-time']) ? '' : explode("-", implode(", ", $customs['business-time']));

$ltAddress = empty($customs['address']) ? '' : implode(",", $customs['address']);
$ltOpen = empty($businessTime) ? '' : trim($businessTime[0]);
$ltClose = empty($businessTime) ? '' : trim($businessTime[1]);
$ltStatus = JATemplateHelper::OpenClosedTime($ltOpen, $ltClose);

?>

<!-- Article -->
<article class="view-listing">
 <?php if ($isUnpublished) : ?>
    <div class="system-unpublished">
  <?php endif; ?>

    <div class="image-wrap">
      <?php echo JLayoutHelper::render('joomla.content.intro_image', $this->item); ?>

      <?php if(!empty($customs['listing-type'])): ?>
        <div class="listing-type">
          <span class="<?php echo implode(",", $customs['listing-type']) ;?>"></span>
        </div>
      <?php endif ;?>
    </div>

    <div class="intro-wrap">
      <div class="top-info">        
        <?php echo LayoutHelper::render('joomla.content.blog_style_default_item_title', $this->item); ?>
      
        <?php if($ltOpen || $ltClose) :?>
          <div class="fs-xs mb-1 stt-time stt-<?php echo strtolower(preg_replace('/\s*/', '', $ltStatus)) ;?>"><?php echo $ltStatus ;?></div>
        <?php endif ;?>

        <?php if($ltAddress) :?>
          <div class="location fs-xs"><?php echo $ltAddress ;?></div>
        <?php endif ;?>

        <?php if (!$params->get('show_intro')) : ?>
          <?php // Content is generated by content plugin event "onContentAfterTitle" ?>
          <?php echo $this->item->event->afterDisplayTitle; ?>
        <?php endif; ?>

        <!-- Aside -->
        <?php if ($topInfo || $icons) : ?>
        <aside class="article-aside clearfix">
          <?php if ($topInfo): ?>
          <?php echo JLayoutHelper::render('joomla.content.info_block.block', array('item' => $this->item, 'params' => $params, 'position' => 'above')); ?>
          <?php endif; ?>
          
          <?php if ($icons): ?>
          <?php echo JLayoutHelper::render('joomla.content.icons', array('item' => $this->item, 'params' => $params)); ?>
          <?php endif; ?>
        </aside>  
        <?php endif; ?>
        <!-- //Aside -->

        <!-- footer -->
        <?php if ($botInfo) : ?>
        <footer class="article-footer clearfix">
          <?php // Todo: for Joomla4 joomla.content.info_block.block can be changed to joomla.content.info_block ?>
          <?php echo JLayoutHelper::render('joomla.content.info_block.block', array('item' => $this->item, 'params' => $params, 'position' => 'below')); ?>
        </footer>
        <?php endif; ?>
        <!-- //footer -->
      </div>

      <div class="bottom-info">
        <!-- Show voting form -->
        <?php if ($params->get('show_vote') && $item->rating_count > 0): ?>
        <div class="rating-detail-wrap">
          <?php
            $scoreNum = '0';
            if($this->item->rating > 0) {
              $scoreNum = $this->item->rating;
            };

            $rateCount = '0';
            if($this->item->rating_count > 0) {
              $rateCount = $this->item->rating_count;
            };

            $scoreRate = 'far fa-star';
            if($scoreNum > 0) {
              $scoreRate = 'fas fa-star-half-alt';
            };

            if($scoreNum == 5) {
              $scoreRate = 'fas fa-star';
            };
          ?> 
            <div class="rating">
              <span class="<?php echo $scoreRate; ?>"></span>
              <span class="label"><?php echo $scoreNum ;?></span>
            </div>
            <div class="number-rating"><?php echo $rateCount.' '.Jtext::_('TPL_REVIEWS'); ?></div>
        </div>
        <?php endif ;?>

        <?php // Content is generated by content plugin event "onContentAfterDisplay" ?>
        <?php echo $this->item->event->afterDisplayContent; ?> 

        <?php if(!empty($customs['games-played'])): ?>
          <div class="games-played">
            <?php echo implode(",", $customs['games-played']) ;?>
          </div>
        <?php endif ;?> 
      </div>

    </div>
  <?php if ($isUnpublished) : ?>
    </div>
  <?php endif; ?>

</article>
<!-- //Article -->


